### DISCUSSION TITLE
How does DIKTAT COMMON work

### DISCUSSION THREAD

**Discussion by lyharrietbui** [cqfn/diKTat#1265] [Q&A] [answered]
Hi Team,
I am trying to configure `diktat` with `spotless` and have some questions about `DIKTAT COMMON`. I am not sure how it is interacting with the system. I currently have it enabled as `false` in the `diktat-analysis.yml` file.
- Is it a rule that can be enabled and disabled?
- If it is disabled, what kotlin version is acceptable?
- If it is enabled, what kotlin version is acceptable?
- Does `diktat` run ktlint? If so, can it be configured to not run ktlint? We want the ktlint config to be controlled separately, e.g. for the excludes and the version.
```
# Common configuration
- name: DIKTAT_COMMON
  enabled: false
  configuration:
    # put your package name here - it will be autofixed and checked
    domainName: org.cqfn.diktat
    # testDirs: test
    # can also use chapter names here (not only numbers)
    # expected values:  disabledChapters: "Naming, Comments, General, Variables, Functions, Classes"
    # or: "1, 2, 3, 4, 5, 6"
    disabledChapters: ""
    testDirs: test
    kotlinVersion: 1.5
```
