### DISCUSSION TITLE
WRONG_INDENTATION: why are extendedIndentOfParameters, extendedIndentAfterOperators, and extendedIndentBeforeDot set to false?

### DISCUSSION THREAD

**Discussion by 0x6675636b796f75676974687562** [cqfn/diKTat#1346] [Q&A] [answered]
As of DiKTat 1.1.1, the default configuration for `WRONG_INDENTATION` looks like this:

```yaml
- name: WRONG_INDENTATION
  enabled: true
  configuration:
    newlineAtEnd: true
    extendedIndentOfParameters: false
    alignedParameters: true
    extendedIndentAfterOperators: false
    extendedIndentBeforeDot: false
    indentationSize: 4
```

i. e. all `extendedIndent*` flags are set to `false` now by default. Why so?
